version: '3.8'
services:
  veilanibot:
    container_name: nestjs_veilani_bot
    image: veilanibot
    network_mode: 'host'
    environment:
      - BOT_TOKEN=6358212073:AAHBRle79uHuFbXYDNcL-2RTE97aSOLOMiI
      - GROUP_CHAT_ID=-1001831838740
    build:
      context: .
    restart: unless-stopped
