version: '3.8'
services:
  veilanibot:
    container_name: nestjs_veilani_bot
    image: veilanibot
    network_mode: 'host'
    environment:
      NODE_ENV: production
    build:
      context: .
    restart: unless-stopped
